[package]
name = "filite"
version = "0.3.0"
authors = ["Raphaël Thériault <raphael_theriault@outlook.com>"]
edition = "2018"
description = "A modular and standalone pastebin, URL shortener and file-sharing service"
homepage = "https://github.com/raftario/filite"
repository = "https://github.com/raftario/filite"
readme = "README.md"
keywords = [
    "file-sharing",
    "url-shortener",
    "pastebin",
]
license = "MIT"

[dependencies]
anyhow = "1.0.31"
cfg-if = "0.1.10"
chrono = "0.4.11"
futures-core = "0.3.5"
futures-util = "0.3.5"
log = { version = "0.4.8", features = ["serde"] }
rust-argon2 = "0.8.2"
serde = { version = "1.0.114", features = ["derive"] }
serde_json = "1.0.55"
sqlx = { version = "0.3.5", features = ["chrono", "macros", "runtime-tokio"], default-features = false }
structopt = "0.3.15"
tokio = { version = "0.2.21", features = ["blocking", "fs", "rt-core"] }
warp = { version = "0.2.3", features = ["multipart"], default-features = false }

# Makes cross-compiliing easier by statically linking to OpenSSL
[target.'cfg(not(any(target_os = "windows", target_os = "macos", target_os = "ios")))'.dependencies]
openssl-sys = { version = "0.9", features = ["vendored"] }

[features]
default = ["full"]
lite = ["sqlite"]
classic = [
    "sqlite",
    "threaded",
    "highlight",
]
full = [
    "sqlite",
    "postgres",
    "mysql",
    "tls",
    "threaded",
    "analytics",
    "highlight",
]

# Database backends
sqlite = ["sqlx/sqlite"]
postgres = ["sqlx/postgres"]
mysql = ["sqlx/mysql"]

# TLS support for the database and web server
tls = [
    "sqlx/tls",
    "warp/tls",
]

# Threaded runtime
threaded = ["tokio/rt-threaded"]

# Various analytics (no external services)
analytics = []

# Syntax highlighting
highlight = []
